const productImages = {
  1: "india-gate-basmati-rice.jpg",
  2: "images/daawat-basmati-rice.jpg",
  3: "images/fortune-biryani-rice.jpg",
  4: "images/ponni-boiled-rice.jpg",
  5: "images/aashirvaad-atta.jpg",
  6: "images/naga-maida.jpg",
  7: "images/naga-rava.jpg",
  8: "images/anil-semiya.jpg",
  9: "images/idiyappam-flour.jpg",
  10: "images/rice-flour.jpg",

  11: "images/toor-dal.jpg",
  12: "images/urad-dal.jpg",
  13: "images/moong-dal.jpg",
  14: "images/chana-dal.jpg",
  15: "images/masoor-dal.jpg",
  16: "images/white-chana.jpg",
  17: "images/rajma.jpg",
  18: "images/black-chana.jpg",
  19: "images/green-gram.jpg",
  20: "images/cowpea.jpg",

  21: "images/fortune-sunflower-oil.jpg",
  22: "images/fortune-rice-bran-oil.jpg",
  23: "images/gold-winner-refined-oil.jpg",
  24: "images/idhayam-ginelly-oil.jpg",
  25: "images/coconut-oil.jpg",
  26: "images/aavin-ghee.jpg",
  27: "images/coconut-ghee.jpg",
  28: "images/mustard-oil.jpg",
  29: "images/olive-oil.jpg",
  30: "images/vanaspati.jpg",

  31: "images/aachi-chilli-powder.jpg",
  32: "images/aachi-sambar-powder.jpg",
  33: "images/aachi-turmeric-powder.jpg",
  34: "images/sakthi-chicken-masala.jpg",
  35: "images/sakthi-garam-masala.jpg",
  36: "images/aachi-rasam-powder.jpg",
  37: "images/aachi-biryani-masala.jpg",
  38: "images/coriander-powder.jpg",
  39: "images/cumin-seeds.jpg",
  40: "images/pepper-seeds.jpg",

  41: "images/bru-instant-coffee.jpg",
  42: "images/three-roses-tea.jpg",
  43: "images/tata-tea-gold.jpg",
  44: "images/avt-premium-tea.jpg",
  45: "images/nescafe-classic-coffee.jpg",
  46: "images/boost-health-drink.jpg",
  47: "images/horlicks-classic-malt.jpg",
  48: "images/bournvita.jpg",
  49: "images/complan-nutrition-drink.jpg",
  50: "images/milo-chocolate-drink.jpg",

  51: "images/tata-salt.jpg",
  52: "images/sugar.jpg",
  53: "images/jaggery.jpg",
  54: "images/palm-jaggery.jpg",
  55: "images/tamarind.jpg",
  56: "images/papad.jpg",
  57: "images/appalam.jpg",
  58: "images/pickle-mango.jpg",
  59: "images/tomato-ketchup.jpg",
  60: "images/kitchen-essentials.jpg",

  61: "images/maggi-masala-noodles.jpg",
  62: "images/yippee-magic-masala-noodles.jpg",
  63: "images/top-ramen-curry-noodles.jpg",
  64: "images/mtr-gulab-jamun-mix.jpg",
  65: "images/aachi-gulab-jamun-mix.jpg",
  66: "images/mtr-rava-idli-mix.jpg",
  67: "images/mtr-upma-mix.jpg",
  68: "images/mtr-poha-mix.jpg",
  69: "images/ready-to-cook-chapathi.jpg",
  70: "images/instant-oats.jpg",

  71: "images/parle-g-biscuits.jpg",
  72: "images/britannia-good-day.jpg",
  73: "images/britannia-marie-gold.jpg",
  74: "images/sunfeast-dark-fantasy.jpg",
  75: "images/oreo-original.jpg",
  76: "images/50-50-biscuits.jpg",
  77: "images/monaco-biscuits.jpg",
  78: "images/little-hearts.jpg",
  79: "images/bourbon-biscuits.jpg",
  80: "images/milk-bikis.jpg",

  81: "images/haldirams-aloo-bhujia.jpg",
  82: "images/haldirams-namkeen.jpg",
  83: "images/bingo-mad-angles.jpg",
  84: "images/lay-s-classic-salted.jpg",
  85: "images/kurkure-masala-munch.jpg",
  86: "images/uncle-chips.jpg",
  87: "images/too-yumm-chips.jpg",
  88: "images/mixture.jpg",
  89: "images/banana-chips.jpg",
  90: "images/murukku.jpg",

  91: "images/whisper-ultra.jpg",
  92: "images/stayfree-xl.jpg",
  93: "images/pampers-diapers.jpg",
  94: "images/huggies-diapers.jpg",
  95: "images/dettol-soap.jpg",
  96: "images/lux-soap.jpg",
  97: "images/hamam-soap.jpg",
  98: "images/colgate-toothpaste.jpg",
  99: "images/closeup-toothpaste.jpg",
  100: "images/pepsodent-toothpaste.jpg",

  101: "images/vim-dishwash-bar.jpg",
  102: "images/vim-liquid.jpg",
  103: "images/surf-excel-detergent.jpg",
  104: "images/ariel-detergent.jpg",
  105: "images/tide-detergent.jpg",
  106: "images/comfort-fabric-conditioner.jpg",
  107: "images/harpic-toilet-cleaner.jpg",
  108: "images/colin-glass-cleaner.jpg",
  109: "images/godrej-aer.jpg",
  110: "images/odonil-room-freshener.jpg",

  111: "images/aavin-milk.jpg",
  112: "images/milk-bikis.jpg",
  113: "images/amul-butter.jpg",
  114: "images/amul-cheese.jpg",
  115: "images/heritage-curd.jpg",
  116: "images/aavin-curd.jpg",
  117: "images/eggs.jpg",
  118: "images/bread.jpg",
  119: "images/modern-bread.jpg",
  120: "images/britannia-cake.jpg",

  121: "images/central-stores-biryani-mix.jpg",
  122: "images/central-stores-elakkai-thool.jpg",
  123: "images/central-stores-pattai.jpg",
  124: "images/central-stores-kirambu.jpg",
  125: "images/central-stores-milagu.jpg",
  126: "images/central-stores-sombu.jpg",
  127: "images/central-stores-star-anise.jpg",
  128: "images/central-stores-kalpaasi.jpg",
  129: "images/central-stores-bay-leaf.jpg",
  130: "images/central-stores-cooking-masala.jpg"
};
