const productImages = {
  1: "india-gate-basmati-rice.jpg",
  2: "daawat-basmati-rice.jpg",
  3: "fortune-biryani-rice.jpg",
  4: "ponni-boiled-rice.jpg",
  5: "aashirvaad-atta.jpg",
  6: "naga-maida.jpg",
  7: "naga-rava.jpg",
  8: "anil-semiya.jpg",
  9: "idiyappam-flour.jpg",
  10: "rice-flour.jpg",

  11: "toor-dal.jpg",
  12: "urad-dal.jpg",
  13: "moong-dal.jpg",
  14: "chana-dal.jpg",
  15: "masoor-dal.jpg",
  16: "white-chana.jpg",
  17: "rajma.jpg",
  18: "black-chana.jpg",
  19: "green-gram.jpg",
  20: "cowpea.jpg",

  21: "fortune-sunflower-oil.jpg",
  22: "fortune-rice-bran-oil.jpg",
  23: "gold-winner-refined-oil.jpg",
  24: "idhayam-ginelly-oil.jpg",
  25: "coconut-oil.jpg",
  26: "aavin-ghee.jpg",
  27: "coconut-ghee.jpg",
  28: "mustard-oil.jpg",
  29: "olive-oil.jpg",
  30: "vanaspati.jpg",

  31: "aachi-chilli-powder.jpg",
  32: "aachi-sambar-powder.jpg",
  33: "aachi-turmeric-powder.jpg",
  34: "sakthi-chicken-masala.jpg",
  35: "sakthi-garam-masala.jpg",
  36: "aachi-rasam-powder.jpg",
  37: "aachi-biryani-masala.jpg",
  38: "coriander-powder.jpg",
  39: "cumin-seeds.jpg",
  40: "pepper-seeds.jpg",

  41: "bru-instant-coffee.jpg",
  42: "three-roses-tea.jpg",
  43: "tata-tea-gold.jpg",
  44: "avt-premium-tea.jpg",
  45: "nescafe-classic-coffee.jpg",
  46: "boost-health-drink.jpg",
  47: "horlicks-classic-malt.jpg",
  48: "bournvita.jpg",
  49: "complan-nutrition-drink.jpg",
  50: "milo-chocolate-drink.jpg",

  51: "tata-salt.jpg",
  52: "sugar.jpg",
  53: "jaggery.jpg",
  54: "palm-jaggery.jpg",
  55: "tamarind.jpg",
  56: "papad.jpg",
  57: "appalam.jpg",
  58: "pickle-mango.jpg",
  59: "tomato-ketchup.jpg",
  60: "kitchen-essentials.jpg",

  61: "maggi-masala-noodles.jpg",
  62: "yippee-magic-masala-noodles.jpg",
  63: "top-ramen-curry-noodles.jpg",
  64: "mtr-gulab-jamun-mix.jpg",
  65: "aachi-gulab-jamun-mix.jpg",
  66: "mtr-rava-idli-mix.jpg",
  67: "mtr-upma-mix.jpg",
  68: "mtr-poha-mix.jpg",
  69: "ready-to-cook-chapathi.jpg",
  70: "instant-oats.jpg",

  71: "parle-g-biscuits.jpg",
  72: "britannia-good-day.jpg",
  73: "britannia-marie-gold.jpg",
  74: "sunfeast-dark-fantasy.jpg",
  75: "oreo-original.jpg",
  76: "50-50-biscuits.jpg",
  77: "monaco-biscuits.jpg",
  78: "little-hearts.jpg",
  79: "bourbon-biscuits.jpg",
  80: "milk-bikis.jpg",

  81: "haldirams-aloo-bhujia.jpg",
  82: "haldirams-namkeen.jpg",
  83: "bingo-mad-angles.jpg",
  84: "lay-s-classic-salted.jpg",
  85: "kurkure-masala-munch.jpg",
  86: "uncle-chips.jpg",
  87: "too-yumm-chips.jpg",
  88: "mixture.jpg",
  89: "banana-chips.jpg",
  90: "murukku.jpg",

  91: "whisper-ultra.jpg",
  92: "stayfree-xl.jpg",
  93: "pampers-diapers.jpg",
  94: "huggies-diapers.jpg",
  95: "dettol-soap.jpg",
  96: "lux-soap.jpg",
  97: "hamam-soap.jpg",
  98: "colgate-toothpaste.jpg",
  99: "closeup-toothpaste.jpg",
  100: "pepsodent-toothpaste.jpg",

  101: "vim-dishwash-bar.jpg",
  102: "vim-liquid.jpg",
  103: "surf-excel-detergent.jpg",
  104: "ariel-detergent.jpg",
  105: "tide-detergent.jpg",
  106: "comfort-fabric-conditioner.jpg",
  107: "harpic-toilet-cleaner.jpg",
  108: "colin-glass-cleaner.jpg",
  109: "godrej-aer.jpg",
  110: "odonil-room-freshener.jpg",

  111: "aavin-milk.jpg",
  112: "milk-bikis.jpg",
  113: "amul-butter.jpg",
  114: "amul-cheese.jpg",
  115: "heritage-curd.jpg",
  116: "aavin-curd.jpg",
  117: "eggs.jpg",
  118: "bread.jpg",
  119: "modern-bread.jpg",
  120: "britannia-cake.jpg",

  121: "central-stores-biryani-mix.jpg",
  122: "central-stores-elakkai-thool.jpg",
  123: "central-stores-pattai.jpg",
  124: "central-stores-kirambu.jpg",
  125: "central-stores-milagu.jpg",
  126: "central-stores-sombu.jpg",
  127: "central-stores-star-anise.jpg",
  128: "central-stores-kalpaasi.jpg",
  129: "central-stores-bay-leaf.jpg",
  130: "central-stores-cooking-masala.jpg"
};
