const productImages = {
  1: "india-gate-basmati-rice.jpg",
  2: "daawat-basmati-rice.jpg",
  3: "fortune-biryani-rice.jpg",
  4: "ponni-rice.jpg",
  5: "aashirvaad-atta.jpg",
  6: "naga-maida.jpg",
  7: "naga-rava.jpg",
  8: "anil-semiya.jpg",
  9: "idiyappam-flour.jpg",
  10: "rice-flour.jpg",

  11: "toor-dal.jpg",
  12: "urad-dal.jpg",
  13: "moong-dal.jpg",
  14: "chana-dal.jpg",
  15: "masoor-dal.jpg",
  16: "white-chana.jpg",
  17: "rajma.jpg",
  18: "black-chana.jpg",
  19: "green-gram.jpg",
  20: "cowpea.jpg",

  21: "fortune-sunflower-oil.jpg",
  22: "fortune-rice-bran-oil.jpg",
  23: "gold-winner-refined-oil.jpg",
  24: "idhayam-ginelly-oil.jpg",
  25: "coconut-oil.jpg",
  26: "aavin-ghee.jpg",
  27: "coconut-ghee.jpg",
  28: "mustard-oil.jpg",
  29: "olive-oil.jpg",
  30: "vanaspati.jpg",

  31: "aachi-chilli-powder.jpg",
  32: "aachi-sambar-powder.jpg",
  33: "aachi-turmeric-powder.jpg",
  34: "sakthi-chicken-masala.jpg",
  35: "sakthi-garam-masala.jpg",
  36: "aachi-rasam-powder.jpg",
  37: "aachi-biryani-masala.jpg",
  38: "coriander-powder.jpg",
  39: "cumin-seeds.jpg",
  40: "pepper-seeds.jpg",

  41: "bru-instant-coffee.jpg",
  42: "three-roses-tea.jpg",
  43: "tata-tea-gold.jpg",
  44: "avt-premium-tea.jpg",
  45: "nescafe-classic-coffee.jpg",
  46: "boost-health-drink.jpg",
  47: "horlicks-classic-malt.jpg",
  48: "bournvita.jpg",
  49: "complan-nutrition-drink.jpg",
  50: "milo-chocolate-drink.jpg",

  51: "tata-salt.jpg",
  52: "sugar.jpg",
  53: "jaggery.jpg",
  54: "palm-jaggery.jpg",
  55: "tamarind.jpg",
  56: "papad.jpg",
  57: "appalam.jpg",
  58: "pickle-mango.jpg",
  59: "tomato-ketchup.jpg",
  60: "kitchen-essentials.jpg",

61: "parle-g-biscuits.jpg",
62: "britannia-good-day.jpg",
63: "britannia-marie-gold.jpg",
64: "sunfeast-dark-fantasy.jpg",
65: "oreo-original.jpg",
66: "50-50-biscuits.jpg",
67: "monaco-biscuits.jpg",
68: "little-hearts.jpg",
69: "bourbon-biscuits.jpg",
70: "milk-bikis.jpg",

71: "ariel-detergent.jpg",
72: "surf-excel-detergent.jpg",
73: "rin-detergent-bar.jpg",
74: "vim-dishwash-bar.jpg",
75: "vim-liquid.jpg",
76: "harpic-toilet-cleaner.jpg",
77: "lizol-floor-cleaner.jpg",
78: "colin-glass-cleaner.jpg",
79: "good-knight-refill.jpg",
80: "scotch-brite-scrub-pad.jpg",

81: "lux-soap.jpg",
82: "dove-beauty-bar.jpg",
83: "lifebuoy-soap.jpg",
84: "pears-soap.jpg",
85: "colgate-toothpaste.jpg",
86: "closeup-toothpaste.jpg",
87: "clinic-plus-shampoo.jpg",
88: "sunsilk-shampoo.jpg",
89: "whisper-sanitary-pads.jpg",
90: "stayfree-sanitary-pads.jpg",

91: "pampers-baby-diapers.jpg",
92: "huggies-baby-diapers.jpg",
93: "johnsons-baby-soap.jpg",
94: "johnsons-baby-powder.jpg",
95: "johnsons-baby-oil.jpg",
96: "cerelac-wheat-apple.jpg",
97: "lactogen-baby-food.jpg",
98: "baby-wipes.jpg",
99: "baby-lotion.jpg",
100: "baby-shampoo.jpg",

101: "britannia-good-day-cashew.jpg",
102: "britannia-marie-gold.jpg",
103: "parle-g-original.jpg",
104: "parle-hide-seek.jpg",
105: "sunfeast-marie-light.jpg",
106: "sunfeast-dark-fantasy.jpg",
107: "sunfeast-moms-magic.jpg",
108: "britannia-50-50-maska-chaska.jpg",
109: "oreo-original-biscuits.jpg",
110: "milk-bikis-classic.jpg",

111: "britannia-bourbon.jpg",
112: "parle-krackjack.jpg",
113: "britannia-nutrichoice-digestive.jpg",
114: "sunfeast-nice-sugar-sprinkle.jpg",
115: "britannia-little-hearts.jpg",

116: "mixture.jpg",
117: "kara-boondi.jpg",
118: "omapodi.jpg",
119: "kai-murukku.jpg",
120: "butter-murukku.jpg",
121: "thattai.jpg",
122: "ribbon-pakoda.jpg",
123: "kara-sev.jpg",
124: "garlic-murukku.jpg",
125: "nendran-banana-chips.jpg",
126: "potato-chips-salted.jpg",
127: "spicy-tapioca-chips.jpg",
128: "masala-groundnut.jpg",
129: "pori-urundai.jpg",
130: "kadalai-mittai.jpg"
};
