const productsData = [
  { id: 1, name: "India Gate Basmati Rice", category: "Rice & Flours", weight: "1 kg" },
  { id: 2, name: "Daawat Basmati Rice", category: "Rice & Flours", weight: "1 kg" },
  { id: 3, name: "Fortune Biryani Special Rice", category: "Rice & Flours", weight: "1 kg" },
  { id: 4, name: "Ponni Boiled Rice", category: "Rice & Flours", weight: "1 kg" },
  { id: 5, name: "Aashirvaad Atta", category: "Rice & Flours", weight: "1 kg" },
  { id: 6, name: "Naga Maida", category: "Rice & Flours", weight: "1 kg" },
  { id: 7, name: "Naga Rava", category: "Rice & Flours", weight: "1 kg" },
  { id: 8, name: "Anil Semiya", category: "Rice & Flours", weight: "400 g" },
  { id: 9, name: "Idiyappam Flour", category: "Rice & Flours", weight: "500 g" },
  { id: 10, name: "Rice Flour", category: "Rice & Flours", weight: "1 kg" },

  { id: 11, name: "Toor Dal", category: "Pulses & Dals", weight: "1 kg" },
  { id: 12, name: "Urad Dal", category: "Pulses & Dals", weight: "1 kg" },
  { id: 13, name: "Moong Dal", category: "Pulses & Dals", weight: "500 g" },
  { id: 14, name: "Chana Dal", category: "Pulses & Dals", weight: "500 g" },
  { id: 15, name: "Masoor Dal", category: "Pulses & Dals", weight: "500 g" },
  { id: 16, name: "White Chana", category: "Pulses & Dals", weight: "500 g" },
  { id: 17, name: "Rajma", category: "Pulses & Dals", weight: "500 g" },
  { id: 18, name: "Black Chana", category: "Pulses & Dals", weight: "500 g" },
  { id: 19, name: "Green Gram", category: "Pulses & Dals", weight: "500 g" },
  { id: 20, name: "Cowpea", category: "Pulses & Dals", weight: "500 g" },

  { id: 21, name: "Fortune Sunflower Oil", category: "Oils & Ghee", weight: "1 L" },
  { id: 22, name: "Fortune Rice Bran Oil", category: "Oils & Ghee", weight: "1 L" },
  { id: 23, name: "Gold Winner Refined Oil", category: "Oils & Ghee", weight: "1 L" },
  { id: 24, name: "Idhayam Gingelly Oil", category: "Oils & Ghee", weight: "1 L" },
  { id: 25, name: "Coconut Oil", category: "Oils & Ghee", weight: "1 L" },
  { id: 26, name: "Aavin Ghee", category: "Oils & Ghee", weight: "500 ml" },
  { id: 27, name: "Cow Ghee", category: "Oils & Ghee", weight: "500 ml" },
  { id: 28, name: "Mustard Oil", category: "Oils & Ghee", weight: "1 L" },
  { id: 29, name: "Olive Oil", category: "Oils & Ghee", weight: "500 ml" },
  { id: 30, name: "Vanaspati", category: "Oils & Ghee", weight: "500 g" },

  { id: 31, name: "Aachi Chilli Powder", category: "Masalas", weight: "200 g" },
  { id: 32, name: "Aachi Sambar Powder", category: "Masalas", weight: "200 g" },
  { id: 33, name: "Aachi Turmeric Powder", category: "Masalas", weight: "100 g" },
  { id: 34, name: "Sakthi Chicken Masala", category: "Masalas", weight: "100 g" },
  { id: 35, name: "Sakthi Garam Masala", category: "Masalas", weight: "100 g" },
  { id: 36, name: "Aachi Rasam Powder", category: "Masalas", weight: "100 g" },
  { id: 37, name: "Aachi Biryani Masala", category: "Masalas", weight: "100 g" },
  { id: 38, name: "Coriander Powder", category: "Masalas", weight: "200 g" },
  { id: 39, name: "Cumin Seeds", category: "Masalas", weight: "100 g" },
  { id: 40, name: "Mustard Seeds", category: "Masalas", weight: "100 g" },

  { id: 41, name: "Bru Instant Coffee", category: "Beverages", weight: "100 g" },
  { id: 42, name: "Three Roses Tea", category: "Beverages", weight: "250 g" },
  { id: 43, name: "Tata Tea Gold", category: "Beverages", weight: "250 g" },
  { id: 44, name: "AVT Premium Tea", category: "Beverages", weight: "250 g" },
  { id: 45, name: "Nescafe Classic Coffee", category: "Beverages", weight: "100 g" },
  { id: 46, name: "Boost Health Drink", category: "Beverages", weight: "500 g" },
  { id: 47, name: "Horlicks Classic Malt", category: "Beverages", weight: "500 g" },
  { id: 48, name: "Bournvita", category: "Beverages", weight: "500 g" },
  { id: 49, name: "Complan Nutrition Drink", category: "Beverages", weight: "500 g" },
  { id: 50, name: "Milo Chocolate Drink", category: "Beverages", weight: "400 g" },

  { id: 51, name: "Tata Salt", category: "Kitchen Essentials", weight: "1 kg" },
  { id: 52, name: "Sugar", category: "Kitchen Essentials", weight: "1 kg" },
  { id: 53, name: "Jaggery", category: "Kitchen Essentials", weight: "500 g" },
  { id: 54, name: "Palm Jaggery", category: "Kitchen Essentials", weight: "500 g" },
  { id: 55, name: "Tamarind", category: "Kitchen Essentials", weight: "500 g" },
  { id: 56, name: "Papad", category: "Kitchen Essentials", weight: "200 g" },
  { id: 57, name: "Appalam", category: "Kitchen Essentials", weight: "200 g" },
  { id: 58, name: "Pickle Mango", category: "Kitchen Essentials", weight: "300 g" },
  { id: 59, name: "Tomato Ketchup", category: "Kitchen Essentials", weight: "500 g" },
  { id: 60, name: "Vinegar", category: "Kitchen Essentials", weight: "500 ml" },

{ id: 61, name: "Parle-G Biscuits", category: "Biscuits", weight: "800 g" },
{ id: 62, name: "Britannia Good Day", category: "Biscuits", weight: "600 g" },
{ id: 63, name: "Britannia Marie Gold", category: "Biscuits", weight: "600 g" },
{ id: 64, name: "Sunfeast Dark Fantasy", category: "Biscuits", weight: "300 g" },
{ id: 65, name: "Oreo Original", category: "Biscuits", weight: "300 g" },
{ id: 66, name: "Britannia 50-50", category: "Biscuits", weight: "300 g" },
{ id: 67, name: "Parle Monaco", category: "Biscuits", weight: "300 g" },
{ id: 68, name: "Little Hearts", category: "Biscuits", weight: "200 g" },
{ id: 69, name: "Britannia Bourbon", category: "Biscuits", weight: "300 g" },
{ id: 70, name: "Milk Bikis", category: "Biscuits", weight: "300 g" },

  { id: 71, name: "Ariel Matic Detergent", category: "Home Care", weight: "1 kg" },
  { id: 72, name: "Surf Excel Easy Wash", category: "Home Care", weight: "1 kg" },
  { id: 73, name: "Rin Detergent Bar", category: "Home Care", weight: "250 g" },
  { id: 74, name: "Vim Dishwash Bar", category: "Home Care", weight: "200 g" },
  { id: 75, name: "Vim Dishwash Liquid", category: "Home Care", weight: "500 ml" },
  { id: 76, name: "Harpic Toilet Cleaner", category: "Home Care", weight: "500 ml" },
  { id: 77, name: "Lizol Floor Cleaner", category: "Home Care", weight: "500 ml" },
  { id: 78, name: "Colin Glass Cleaner", category: "Home Care", weight: "500 ml" },
  { id: 79, name: "Good Knight Refill", category: "Home Care", weight: "45 ml" },
  { id: 80, name: "Scotch Brite Scrub Pad", category: "Home Care", weight: "1 pack" },

  { id: 81, name: "Lux Soap", category: "Personal Care", weight: "100 g" },
  { id: 82, name: "Dove Beauty Bar", category: "Personal Care", weight: "100 g" },
  { id: 83, name: "Lifebuoy Soap", category: "Personal Care", weight: "125 g" },
  { id: 84, name: "Pears Soap", category: "Personal Care", weight: "125 g" },
  { id: 85, name: "Colgate Toothpaste", category: "Personal Care", weight: "200 g" },
  { id: 86, name: "Closeup Toothpaste", category: "Personal Care", weight: "150 g" },
  { id: 87, name: "Clinic Plus Shampoo", category: "Personal Care", weight: "180 ml" },
  { id: 88, name: "Sunsilk Shampoo", category: "Personal Care", weight: "180 ml" },
  { id: 89, name: "Whisper Sanitary Pads", category: "Personal Care", weight: "8 pads" },
  { id: 90, name: "Stayfree Sanitary Pads", category: "Personal Care", weight: "8 pads" },

  { id: 91, name: "Pampers Baby Diapers", category: "Baby Care", weight: "10 pieces" },
  { id: 92, name: "Huggies Baby Diapers", category: "Baby Care", weight: "10 pieces" },
  { id: 93, name: "Johnson's Baby Soap", category: "Baby Care", weight: "75 g" },
  { id: 94, name: "Johnson's Baby Powder", category: "Baby Care", weight: "100 g" },
  { id: 95, name: "Johnson's Baby Oil", category: "Baby Care", weight: "100 ml" },
  { id: 96, name: "Cerelac Wheat Apple", category: "Baby Care", weight: "300 g" },
  { id: 97, name: "Lactogen Baby Formula", category: "Baby Care", weight: "400 g" },
  { id: 98, name: "Baby Wipes", category: "Baby Care", weight: "72 wipes" },
  { id: 99, name: "Baby Lotion", category: "Baby Care", weight: "200 ml" },
  { id: 100, name: "Baby Shampoo", category: "Baby Care", weight: "200 ml" },

  { id: 101, name: "Britannia Good Day Cashew", category: "Biscuits", weight: "200 g" },
  { id: 102, name: "Britannia Marie Gold", category: "Biscuits", weight: "250 g" },
  { id: 103, name: "Parle-G Original", category: "Biscuits", weight: "800 g" },
  { id: 104, name: "Parle Hide & Seek", category: "Biscuits", weight: "100 g" },
  { id: 105, name: "Sunfeast Marie Light", category: "Biscuits", weight: "250 g" },
  { id: 106, name: "Sunfeast Dark Fantasy", category: "Biscuits", weight: "75 g" },
  { id: 107, name: "Sunfeast Mom's Magic", category: "Biscuits", weight: "200 g" },
  { id: 108, name: "Britannia 50-50 Maska Chaska", category: "Biscuits", weight: "100 g" },
  { id: 109, name: "Oreo Original Biscuits", category: "Biscuits", weight: "120 g" },
  { id: 110, name: "Milk Bikis Classic", category: "Biscuits", weight: "200 g" },
  { id: 111, name: "Britannia Bourbon", category: "Biscuits", weight: "150 g" },
  { id: 112, name: "Parle KrackJack", category: "Biscuits", weight: "200 g" },
  { id: 113, name: "Britannia NutriChoice Digestive", category: "Biscuits", weight: "200 g" },
  { id: 114, name: "Sunfeast Nice Sugar Sprinkle", category: "Biscuits", weight: "150 g" },
  { id: 115, name: "Britannia Little Hearts", category: "Biscuits", weight: "75 g" },

  { id: 116, name: "Mixture", category: "Tamil Nadu Snacks", weight: "200 g" },
  { id: 117, name: "Kara Boondi", category: "Tamil Nadu Snacks", weight: "200 g" },
  { id: 118, name: "Omapodi", category: "Tamil Nadu Snacks", weight: "200 g" },
  { id: 119, name: "Kai Murukku", category: "Tamil Nadu Snacks", weight: "200 g" },
  { id: 120, name: "Butter Murukku", category: "Tamil Nadu Snacks", weight: "200 g" },
  { id: 121, name: "Thattai", category: "Tamil Nadu Snacks", weight: "200 g" },
  { id: 122, name: "Ribbon Pakoda", category: "Tamil Nadu Snacks", weight: "200 g" },
  { id: 123, name: "Kara Sev", category: "Tamil Nadu Snacks", weight: "200 g" },
  { id: 124, name: "Garlic Murukku", category: "Tamil Nadu Snacks", weight: "200 g" },
  { id: 125, name: "Nendran Banana Chips", category: "Tamil Nadu Snacks", weight: "150 g" },
  { id: 126, name: "Potato Chips Salted", category: "Tamil Nadu Snacks", weight: "150 g" },
  { id: 127, name: "Spicy Tapioca Chips", category: "Tamil Nadu Snacks", weight: "150 g" },
  { id: 128, name: "Masala Groundnut", category: "Tamil Nadu Snacks", weight: "200 g" },
  { id: 129, name: "Pori Urundai", category: "Tamil Nadu Snacks", weight: "150 g" },
  { id: 130, name: "Kadalai Mittai", category: "Tamil Nadu Snacks", weight: "150 g" }
];
