const productsData = [
  // RICE & FLOURS
  { id: 1, name: "India Gate Basmati Rice", category: "Rice & Flours", weight: "1 kg" },
  { id: 2, name: "Daawat Basmati Rice", category: "Rice & Flours", weight: "1 kg" },
  { id: 3, name: "Fortune Biryani Special Rice", category: "Rice & Flours", weight: "1 kg" },
  { id: 4, name: "Ponni Boiled Rice", category: "Rice & Flours", weight: "1 kg" },
  { id: 5, name: "Idli Rice", category: "Rice & Flours", weight: "1 kg" },
  { id: 6, name: "Raw Rice", category: "Rice & Flours", weight: "1 kg" },
  { id: 7, name: "Aashirvaad Atta", category: "Rice & Flours", weight: "1 kg" },
  { id: 8, name: "Naga Maida", category: "Rice & Flours", weight: "1 kg" },
  { id: 9, name: "Naga Rava", category: "Rice & Flours", weight: "500 g" },
  { id: 10, name: "Anil Semiya", category: "Rice & Flours", weight: "400 g" },

  // PULSES & DALS
  { id: 11, name: "Toor Dal Premium", category: "Pulses & Dals", weight: "1 kg" },
  { id: 12, name: "Urad Dal", category: "Pulses & Dals", weight: "1 kg" },
  { id: 13, name: "Moong Dal", category: "Pulses & Dals", weight: "500 g" },
  { id: 14, name: "Chana Dal", category: "Pulses & Dals", weight: "500 g" },
  { id: 15, name: "Masoor Dal", category: "Pulses & Dals", weight: "500 g" },
  { id: 16, name: "Rajma", category: "Pulses & Dals", weight: "500 g" },
  { id: 17, name: "White Chana", category: "Pulses & Dals", weight: "500 g" },
  { id: 18, name: "Black Chana", category: "Pulses & Dals", weight: "500 g" },
  { id: 19, name: "Green Gram", category: "Pulses & Dals", weight: "500 g" },
  { id: 20, name: "Kollu Horse Gram", category: "Pulses & Dals", weight: "500 g" },

  // OILS & GHEE
  { id: 21, name: "Fortune Sunflower Oil", category: "Oils & Ghee", weight: "1 L" },
  { id: 22, name: "Gold Winner Refined Oil", category: "Oils & Ghee", weight: "1 L" },
  { id: 23, name: "Idhayam Gingelly Oil", category: "Oils & Ghee", weight: "1 L" },
  { id: 24, name: "Coconut Oil", category: "Oils & Ghee", weight: "500 ml" },
  { id: 25, name: "Aavin Ghee", category: "Oils & Ghee", weight: "200 ml" },
  { id: 26, name: "Cow Ghee", category: "Oils & Ghee", weight: "500 ml" },
  { id: 27, name: "Groundnut Oil", category: "Oils & Ghee", weight: "1 L" },
  { id: 28, name: "Mustard Oil", category: "Oils & Ghee", weight: "1 L" },
  { id: 29, name: "Fortune Rice Bran Oil", category: "Oils & Ghee", weight: "1 L" },
  { id: 30, name: "Vanaspati", category: "Oils & Ghee", weight: "500 g" },

  // MASALAS
  { id: 31, name: "Aachi Chilli Powder", category: "Masalas", weight: "200 g" },
  { id: 32, name: "Aachi Sambar Powder", category: "Masalas", weight: "200 g" },
  { id: 33, name: "Aachi Rasam Powder", category: "Masalas", weight: "100 g" },
  { id: 34, name: "Sakthi Turmeric Powder", category: "Masalas", weight: "100 g" },
  { id: 35, name: "Sakthi Coriander Powder", category: "Masalas", weight: "200 g" },
  { id: 36, name: "Everest Garam Masala", category: "Masalas", weight: "100 g" },
  { id: 37, name: "MTR Chicken Masala", category: "Masalas", weight: "100 g" },
  { id: 38, name: "Aachi Biryani Masala", category: "Masalas", weight: "100 g" },
  { id: 39, name: "Black Pepper", category: "Masalas", weight: "100 g" },
  { id: 40, name: "Jeera Cumin", category: "Masalas", weight: "100 g" },

  // BEVERAGES
  { id: 41, name: "Three Roses Tea", category: "Beverages", weight: "250 g" },
  { id: 42, name: "AVT Premium Tea", category: "Beverages", weight: "250 g" },
  { id: 43, name: "Tata Tea Gold", category: "Beverages", weight: "250 g" },
  { id: 44, name: "Bru Instant Coffee", category: "Beverages", weight: "100 g" },
  { id: 45, name: "Nescafe Classic Coffee", category: "Beverages", weight: "100 g" },
  { id: 46, name: "Horlicks Classic Malt", category: "Beverages", weight: "500 g" },
  { id: 47, name: "Bournvita", category: "Beverages", weight: "500 g" },
  { id: 48, name: "Boost", category: "Beverages", weight: "500 g" },
  { id: 49, name: "Complan Nutrition Drink", category: "Beverages", weight: "500 g" },
  { id: 50, name: "Milo", category: "Beverages", weight: "400 g" },

  // BISCUITS & SNACKS
  { id: 51, name: "Britannia Good Day", category: "Biscuits & Snacks", weight: "200 g" },
  { id: 52, name: "Britannia Marie Gold", category: "Biscuits & Snacks", weight: "250 g" },
  { id: 53, name: "Parle-G Biscuits", category: "Biscuits & Snacks", weight: "800 g" },
  { id: 54, name: "Sunfeast Dark Fantasy", category: "Biscuits & Snacks", weight: "75 g" },
  { id: 55, name: "Sunfeast Mom's Magic", category: "Biscuits & Snacks", weight: "200 g" },
  { id: 56, name: "Haldiram's Aloo Bhujia", category: "Biscuits & Snacks", weight: "200 g" },
  { id: 57, name: "Bingo Mad Angles", category: "Biscuits & Snacks", weight: "100 g" },
  { id: 58, name: "Lays Classic Salted", category: "Biscuits & Snacks", weight: "52 g" },
  { id: 59, name: "Kurkure Masala Munch", category: "Biscuits & Snacks", weight: "90 g" },
  { id: 60, name: "Too Yumm Chips", category: "Biscuits & Snacks", weight: "75 g" },

  // NOODLES & PASTA
  { id: 61, name: "Maggi 2-Minute Noodles", category: "Noodles & Pasta", weight: "280 g" },
  { id: 62, name: "Yippee Magic Masala Noodles", category: "Noodles & Pasta", weight: "280 g" },
  { id: 63, name: "Top Ramen Curry Noodles", category: "Noodles & Pasta", weight: "280 g" },
  { id: 64, name: "Ching's Secret Hakka Noodles", category: "Noodles & Pasta", weight: "200 g" },
  { id: 65, name: "Ching's Schezwan Chutney", category: "Noodles & Pasta", weight: "250 g" },
  { id: 66, name: "MTR Macaroni", category: "Noodles & Pasta", weight: "200 g" },
  { id: 67, name: "Anil Macaroni", category: "Noodles & Pasta", weight: "400 g" },
  { id: 68, name: "Del Monte Pasta", category: "Noodles & Pasta", weight: "500 g" },
  { id: 69, name: "Kissan Tomato Ketchup", category: "Noodles & Pasta", weight: "500 g" },
  { id: 70, name: "Veeba Mayonnaise", category: "Noodles & Pasta", weight: "250 g" },

  // SUGAR SALT & SWEETENERS
  { id: 71, name: "Tata Salt", category: "Sugar, Salt & Sweeteners", weight: "1 kg" },
  { id: 72, name: "Aashirvaad Salt", category: "Sugar, Salt & Sweeteners", weight: "1 kg" },
  { id: 73, name: "White Sugar", category: "Sugar, Salt & Sweeteners", weight: "1 kg" },
  { id: 74, name: "Karuppatti Palm Jaggery", category: "Sugar, Salt & Sweeteners", weight: "500 g" },
  { id: 75, name: "Vellam Jaggery", category: "Sugar, Salt & Sweeteners", weight: "500 g" },
  { id: 76, name: "Mishri Sugar Candy", category: "Sugar, Salt & Sweeteners", weight: "200 g" },
  { id: 77, name: "Brown Sugar", category: "Sugar, Salt & Sweeteners", weight: "500 g" },
  { id: 78, name: "Honey", category: "Sugar, Salt & Sweeteners", weight: "250 g" },
  { id: 79, name: "Maple Syrup", category: "Sugar, Salt & Sweeteners", weight: "250 ml" },
  { id: 80, name: "Sugar Free Gold", category: "Sugar, Salt & Sweeteners", weight: "100 tablets" },

  // PERSONAL CARE
  { id: 81, name: "Pears Soap", category: "Personal Care", weight: "125 g" },
  { id: 82, name: "Lux Soap", category: "Personal Care", weight: "100 g" },
  { id: 83, name: "Dove Soap", category: "Personal Care", weight: "100 g" },
  { id: 84, name: "Colgate Strong Teeth", category: "Personal Care", weight: "200 g" },
  { id: 85, name: "Closeup Toothpaste", category: "Personal Care", weight: "150 g" },
  { id: 86, name: "Clinic Plus Shampoo", category: "Personal Care", weight: "340 ml" },
  { id: 87, name: "Sunsilk Shampoo", category: "Personal Care", weight: "340 ml" },
  { id: 88, name: "Pond's Talcum Powder", category: "Personal Care", weight: "300 g" },
  { id: 89, name: "Whisper Sanitary Pads", category: "Personal Care", weight: "8 pads" },
  { id: 90, name: "Stayfree Sanitary Pads", category: "Personal Care", weight: "8 pads" },

  // HOME CARE
  { id: 91, name: "Surf Excel Detergent Powder", category: "Home Care", weight: "1 kg" },
  { id: 92, name: "Ariel Matic Detergent", category: "Home Care", weight: "1 kg" },
  { id: 93, name: "Rin Detergent Bar", category: "Home Care", weight: "250 g" },
  { id: 94, name: "Vim Dishwash Bar", category: "Home Care", weight: "300 g" },
  { id: 95, name: "Vim Dishwash Liquid", category: "Home Care", weight: "500 ml" },
  { id: 96, name: "Harpic Toilet Cleaner", category: "Home Care", weight: "500 ml" },
  { id: 97, name: "Lizol Floor Cleaner", category: "Home Care", weight: "500 ml" },
  { id: 98, name: "Good Knight Refill", category: "Home Care", weight: "45 ml" },
  { id: 99, name: "Odonil Room Freshener", category: "Home Care", weight: "75 g" },
  { id: 100, name: "Scotch Brite Scrub Pad", category: "Home Care", weight: "1 pack" }
];
